language: node_js
node_js:
  - "8"
cache:
  directories:
  - node_modules
install:
    - yarn install
    - yarn run build:prerender
script: echo "npm test temporarily disabled"
after_success: |
    cd dist/browser
    mkdir backup
    cd backup
    git clone https://$GITHUB_USER:$GITHUB_API_KEY@github.com/jagyas/backup.git .
    rm -rf *
    git add .
    git commit -m"Removed old backup"
    git push https://$GITHUB_USER:$GITHUB_API_KEY@github.com/jagyas/backup.git master
    echo "Old backup remove complete from backup git"
    cd ..
    mkdir new_clone
    cd new_clone
    git clone https://$GITHUB_USER:$GITHUB_API_KEY@github.com/jagyas/jagyas.github.io .
    rsync -av --exclude='.git' . ../backup
    cd ../backup
    git add .
    git commit -m"New backup commit"
    git push https://$GITHUB_USER:$GITHUB_API_KEY@github.com/jagyas/backup.git master
    echo "New backup copied in backup git"
    cd ..
    mkdir educate
    cd educate
    git clone https://$GITHUB_USER:$GITHUB_API_KEY@github.com/jagyas/jagyas.github.io .
    rm -rf *
    echo "Please wait upgrading. Refresh after few minutes" > index.html
    git add .
    git commit -m"Removed old Educate version"
    git push https://$GITHUB_USER:$GITHUB_API_KEY@github.com/jagyas/jagyas.github.io master
    echo "Old educate version removed"
    cd ..
    rsync -av --exclude='educate' --exclude='new_clone' --exclude='educate' . educate
    cd educate
    git add .
    git commit -m"Committed new Educate version"
    git push https://$GITHUB_USER:$GITHUB_API_KEY@github.com/jagyas/jagyas.github.io master
    echo "New educate version committed"
 
branches:
  only:
  - master