language: node_js
node_js:
  - "8"
cache:
  directories:
  - node_modules
install:
    - yarn install
    - yarn run build:prerender
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_API_KEY  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master