language: node_js
node_js:
  - "8"
cache:
  directories:
  - node_modules
install:
    - yarn install
    - yarn run build:prerender
script: echo "npm test temporarily disabled"
after_success: |
    cd dist/browser
    mkdir backup
    cd backup
    git clone https://$GITHUB_USER:$GITHUB_API_KEY@github.com/jagyas/backup.git .
    rm -rf .
    git add .
    git commit -m"Removed old backup"
    git push https://$GITHUB_USER:$GITHUB_API_KEY@github.com/jagyas/backup.git master
    git clone https://$GITHUB_USER:$GITHUB_API_KEY@github.com/jagyas/jagyas.github.io .
    git remote add origin https://github.com/jagyas/backup.git
    git add .
    git commit -m"New backup commit"
    git push https://$GITHUB_USER:$GITHUB_API_KEY@github.com/jagyas/backup.git master
    cd ..
    mkdir educate
    cd educate
    git clone https://$GITHUB_USER:$GITHUB_API_KEY@github.com/jagyas/jagyas.github.io .
    rm -rf .
    echo "Please wait upgrading. Refresh after few minutes" > index.html
    git add .
    git commit -m"Removed old Educate version"
    git push https://$GITHUB_USER:$GITHUB_API_KEY@github.com/jagyas/jagyas.github.io master
    cd ..
    cp -rf . educate
    cd educate
    git add .
    git commit -m"Committed new Educate version"
    git push https://$GITHUB_USER:$GITHUB_API_KEY@github.com/jagyas/jagyas.github.io master
 
branches:
  only:
  - master